name: page_flip_builder
description: A custom Flutter widget that enables interactive page-flip transitions in your app.
version: 0.1.4
homepage: https://codewithandrea.com/
repository: https://github.com/bizz84/page_flip_builder

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
